# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Minhuan Li <br>(李黾奂)
tagline:          'Minhuan Li'
description:      'And i am floating in a <br>most perculiar way'
#url:              http://minhuanli.github.io

excerpt_separator: <!--more-->  # you can specify your own separator, of course.
author:
  name:           'Minhuan Li'
  #url:            http://minhuanli.github.io

paginate:         5
#google_analytics: 'UA-91425204-3'
#bing_seo:		  'ECA8D4503D79297E7BB223666F18CAF8'
emailme:          mailto:minhuanli@g.harvard.edu

gems:             [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

github:
  repo:           https://github.com/minhuanli/minhuanli.github.io

tags:

github_username:  minhuanli
google_scholar_url: https://scholar.google.com/citations?user=zls7LKwAAAAJ&hl=en
#facebook_username:
#linkedin_username:


