# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Minhuan Li <br>(李黾奂)
tagline:          'Minhuan Li'
description:      'And i am floating in a most perculiar way'
url:              http://minhuanli.github.io

author:
  name:           'Minhuan Li'
  url:            http://minhuanli.github.io

#paginate:         2
#google_analytics: 'UA-91425204-3'
#bing_seo:		  'ECA8D4503D79297E7BB223666F18CAF8'
emailme:          mailto:minhuanli@g.harvard.edu

gems:             [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

github:
  repo:           https://github.com/minhuanli/minhuanli.github.io

tags:

github_username:  minhuanli
#facebook_username: joe.qian
#linkedin_username: long-qian


